<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TypeBeat.Resources\TypeBeat.Resources.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ppy.osu.Framework" Version="2025.1008.0" />
    <PackageReference Include="ppy.osu.Game.Resources" Version="2025.1006.0" />
    <PackageReference Include="supabase-csharp" Version="0.16.2" />
    <PackageReference Include="Clowd.Squirrel" Version="2.11.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Configuration\appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>